name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]
        then
          pyinstaller --onefile --windowed --noconfirm --clean PALMS.py --icon bell_icon.icns
        else
          pyinstaller --onefile --windowed --noconfirm --clean PALMS.py
        fi
      shell: bash

    - name: Archive Linux executable
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: mv dist/PALMS ./PALMS

    - name: Archive Windows executable
      if: ${{ matrix.os == 'windows-latest' }}
      run: mv dist/PALMS.exe ./PALMS_windows.exe

    - name: Archive MacOS executable
      if: ${{ matrix.os == 'macos-latest' }}
      run: mv dist/PALMS ./PALMS_macos

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-executable
        path: |
          ./PALMS
          ./PALMS_windows.exe
          ./PALMS_macos
