name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        PYINSTALLER=
          pyinstaller \
            --onefile --windowed --noconfirm --clean \
            --exclude-module PyQt6.QtWebEngineCore \
            --exclude-module PyQt6.Qt3DCore \
            --exclude-module PyQt6.QtNetwork \
            --exclude-module PyQt6.QtHelp \
            --exclude-module PyQt6.QtPrintSupport \
            --exclude-module PyQt6.QtSensors \
            --exclude-module PyQt6.QtTest \
            --exclude-module PyQt6.QtSvg \
            --exclude-module PyQt6.QtXml --exclude-module PyQt6.QtXmlPatterns \
            --exclude-module PyQt6.QtPositioning \
            --exclude-module tkinter \
            --exclude-module unittest \
            --exclude-module email --exclude-module html \
            --exclude-module http --exclude-module xmlrpc \
            --exclude-module matplotlib.tests --exclude-module mpl_toolkits.tests \
            --exclude-module scipy.spatial --exclude-module scipy.special --exclude-module scipy.stats \
            --exclude-module pandas.tests --exclude-module numpy.testing \
            --exclude-module IPython --exclude-module jupyter \
            --exclude-module pytz --exclude-module tzdata --exclude-module python-dateutil --exclude-module six \
            --exclude-module contourpy --exclude-module cycler --exclude-module fonttools --exclude-module kiwisolver --exclude-module pillow --exclude-module pyparsing \
            --exclude-module ipdb \
            PALMS.py

        if [[ "${{ matrix.os }}" == "macos-latest" ]]
        then
          $PYINSTALLER --icon bell_icon.icns
        elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]
        then
          $PYINSTALLER
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          $PYINSTALLER
        fi
      shell: bash

    - name: Prepare release directory
      run: mkdir -p release

    - name: Archive Linux executable
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        mv dist/PALMS ./release/PALMS_linux
        chmod +x ./release/PALMS_linux

    - name: Archive Windows executable
      if: ${{ matrix.os == 'windows-latest' }}
      run: mv dist/PALMS.exe ./release/PALMS_windows.exe

    - name: Archive MacOS executable
      if: ${{ matrix.os == 'macos-latest' }}
      run: mv dist/PALMS ./release/PALMS_macos

    - name: Copy Experiments directory to release
      run: cp -r Experiments ./release/

    - name: Tag latest commit
      if: github.ref == 'refs/heads/main'
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        tag_name: 'latest'
        tag_message: 'Latest build'

    - name: Upload all release files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-release
        path: release/

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: release/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
