name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        PYINSTALLER="
          pyinstaller
            --onefile --windowed --noconfirm --clean
            --exclude-module PyQt6.QtWebEngineCore
            --exclude-module PyQt6.Qt3DCore
            --exclude-module PyQt6.QtNetwork
            --exclude-module PyQt6.QtHelp
            --exclude-module PyQt6.QtPrintSupport
            --exclude-module PyQt6.QtSensors
            --exclude-module PyQt6.QtTest
            --exclude-module PyQt6.QtSvg
            --exclude-module PyQt6.QtXml --exclude-module PyQt6.QtXmlPatterns
            --exclude-module PyQt6.QtPositioning
            --exclude-module tkinter
            --exclude-module unittest
            --exclude-module email --exclude-module html
            --exclude-module http --exclude-module xmlrpc
            --exclude-module logging
            --exclude-module matplotlib.tests
            --exclude-module numpy.testing
            --strip PALMS.py
          "

        if [[ "${{ matrix.os }}" == "macos-latest" ]]
        then
          PYINSTALLER="$PYINSTALLER --icon bell_icon.icns"
        fi
        $PYINSTALLER
      shell: bash

    - name: Archive Linux executable
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        mv dist/PALMS ./PALMS
        chmod +x ./PALMS

    - name: Archive Windows executable
      if: ${{ matrix.os == 'windows-latest' }}
      run: mv dist/PALMS.exe ./PALMS_windows.exe

    - name: Archive MacOS executable
      if: ${{ matrix.os == 'macos-latest' }}
      run: mv dist/PALMS ./PALMS_macos

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-executable
        path: |
          ./PALMS
          ./PALMS_windows.exe
          ./PALMS_macos
