name: Build Executables

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install Linux dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1-mesa \
          libgles2-mesa-dev \
          libxcb-xinerama0 \
          libxkbcommon-x11-0 \
          libgl1-mesa-glx \
          libgl1-mesa-dri \
          libxi6 \
          libxrender1 \
          libxtst6 \
          libgtk-3-0 \
          gtk2-engines-murrine gtk2-engines-pixbuf
        export DISPLAY=:0
        export WAYLAND_DISPLAY=

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        export QT_QPA_PLATFORM=xcb
        export QT_STYLE_OVERRIDE=Fusion
        EXCLUDED_MODULE_OPTIONS=" \
          --exclude-module PyQt5  \
          --exclude-module PyQt6.Qt6.translations  \
          --exclude-module PyQt6.Qt6.lib.libQt6Pdf  \
          --exclude-module PyQt6.Qt6.lib.libicudata  \
          --exclude-module PyQt6.Qt6.Qt6Network \
          --collect-data PyQt6.Qt6.plugins
        "
        COMMON_OPTIONS="--windowed --noconfirm --clean"

        if [[ "${{ matrix.os }}" == "macos-latest" ]]
        then
          pyinstaller ${EXCLUDED_MODULE_OPTIONS} ${COMMON_OPTIONS} --add-data "resources/palms.png:resources" --onedir --icon resources/palms.icns PALMS.py
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          pyinstaller ${EXCLUDED_MODULE_OPTIONS} ${COMMON_OPTIONS} --add-data "resources\palms.png;resources" --onefile --icon resources/palms.ico PALMS.py
        else
          pyinstaller ${EXCLUDED_MODULE_OPTIONS} ${COMMON_OPTIONS} --add-data "resources/palms.png:resources" --onefile --icon resources/palms.png PALMS.py
        fi
      shell: bash

    - name: Prepare release directory
      run: mkdir -p release

    - name: Archive Linux executable
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        chmod +x dist/PALMS
        tar -czf release_linux.tar.gz Experiments -C dist PALMS

    - name: Archive Windows executable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        tar -czf release_windows.tar.gz Experiments -C dist PALMS.exe

    - name: Archive MacOS executable
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        tar -czf release_macos.tar.gz Experiments -C dist ./

    - name: Commit 'latest' rag.
      if: github.ref == 'refs/heads/release'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -f latest
        git push origin latest --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload all release files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-release
        path: release_*

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: release_*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Github Release, attempt 2
      if: failure()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: release_*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Github Release, attempt 3
      if: failure()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: release_*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-latest-release
        path: release/

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-latest-release
        path: release/

    - name: Download MacOS Artifacts
      uses: actions/download-artifact@v3
      with:
        name: macos-latest-release
        path: release/

    - name: Compress and upload the code to release
      run: |
        tar -czf release/PALMS.tar.gz *.py resources/* LICENSE README.md NOTICE requirements.txt
        cp LICENSE README.md NOTICE release/

    - name: Move the source to their own release
      run: |
        mkdir src/
        cp -r *.py resources/* LICENSE README.md NOTICE requirements.txt src/

    - name: Add licence and readme to release
      run: |
        cp LICENSE README.md NOTICE release/

    - name: Upload compressed release to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
        filename: "release/*"
        folderId: "1QjG6dqdkbLWsDiG5VYiDQLlOj_v-N6ia"
        overwrite: "true"

    - name: Upload uncompressed release to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
        filename: "src/*"
        folderId: "1iKHk-qoPL-LnKDJsgHDRbxpnRMdQ4UT_"
        overwrite: "true"
